# Generated by Django 5.2.5 on 2025-09-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_rename_categories_examdayavailability_trades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='examassignment',
            options={'verbose_name': 'Exam assignment', 'verbose_name_plural': 'Exam assignments'},
        ),
        migrations.AlterModelOptions(
            name='examattempt',
            options={'verbose_name': 'Exam attempt', 'verbose_name_plural': 'Exam attempts'},
        ),
        migrations.AlterModelOptions(
            name='examdayavailability',
            options={'verbose_name': 'Exam day availability', 'verbose_name_plural': 'Exam day availabilities'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Exam slot', 'verbose_name_plural': 'Exam slots'},
        ),
    ]
