# Generated by Django 5.2.5 on 2025-09-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_answer_options_alter_examassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='capacity',
        ),
    ]
