# Generated by Django 5.2.5 on 2025-09-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_remove_center_address_remove_center_capacity_and_more'),
        ('exams', '0006_remove_shift_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='center',
            new_name='exam_center',
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('exam_center', 'date', 'start_time')},
        ),
    ]
