# Generated by Django 5.2.5 on 2025-09-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CENTER_ADMIN', 'Center Admin'), ('CANDIDATE', 'Candidate'), ('PO_ADMIN', 'PO Admin')], db_index=True, default='CANDIDATE', max_length=32),
        ),
    ]
