# Generated by Django 5.2.5 on 2025-09-01 09:05

import django.db.models.deletion
import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_remove_question_level_remove_question_qf_and_more'),
        ('reference', '0005_delete_level_delete_qf_delete_qualification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='questionpaper',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='questionupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='questionupload',
            name='trade',
            field=models.ForeignKey(blank=True, help_text='If set, all imported questions will be tagged with this trade.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.trade'),
        ),
        migrations.AlterField(
            model_name='question',
            name='part',
            field=models.CharField(choices=[('A', 'Part A - MCQ (Single Choice)'), ('B', 'Part B - MCQ (Multiple Choice)'), ('C', 'Part C - MCQ (Other format)'), ('D', 'Part D - Fill in the blanks'), ('E', 'Part E - Long answer (100-120 words)'), ('F', 'Part F - True/False')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='questionupload',
            name='file',
            field=models.FileField(upload_to='uploads/questions/', validators=[questions.models.validate_dat_file]),
        ),
    ]
