# Generated by Django 5.2.5 on 2025-09-04 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_question_options_alter_questionpaper_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionpaper',
            options={'ordering': ['-id'], 'verbose_name': 'QP Mapping', 'verbose_name_plural': 'QP Mappings'},
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='upload',
            new_name='qp_assign',
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='title',
            new_name='question_paper',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='active_from',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='active_to',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='duration',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='exam_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=10800), help_text='Enter exam duration in format HH:MM:SS (e.g., 01:30:00 for 1h30m)', null=True),
        ),
    ]
