# Generated by Django 5.2.5 on 2025-09-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_questionpaper_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'QP Upload', 'verbose_name_plural': 'QP Upload'},
        ),
    ]
