# Generated by Django 5.2.5 on 2025-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_alter_questionupload_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='is_common',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='question_paper',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary', help_text='Select whether this is a Primary or Secondary paper', max_length=20),
        ),
    ]
