# Generated by Django 4.2 on 2025-09-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_alter_questionpaper_is_common_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'QP Delete', 'verbose_name_plural': 'QP Delete'},
        ),
    ]
