# Generated by Django 5.2.5 on 2025-09-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_alter_trade_code_alter_trade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
