# Generated by Django 5.2.5 on 2025-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_candidateprofile_enrolment_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='practical_marks',
            new_name='primary_practical_marks',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='viva_marks',
            new_name='primary_viva_marks',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_practical_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_viva_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
