# Generated by Django 5.2.5 on 2025-09-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_delete_level_delete_qf_delete_qualification_and_more'),
        ('registration', '0007_rename_practical_marks_candidateprofile_primary_practical_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.trade'),
        ),
    ]
