# Generated by Django 5.2.5 on 2025-09-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_candidateprofile_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='qualification',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='primary_credits',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='primary_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='primary_qualification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_credits',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_qualification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
