# Generated by Django 5.2.5 on 2025-09-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_candidateprofile_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='brigade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='command',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='corps',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
