# Generated by Django 5.2.5 on 2025-09-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_candidateprofile_brigade_candidateprofile_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='dob',
            field=models.CharField(max_length=10, verbose_name='Date of Birth'),
        ),
    ]
