# Generated by Django 4.2 on 2025-09-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_candidateprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='primary_practical_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='primary_viva_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='secondary_practical_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='secondary_viva_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
