# Generated by Django 5.2.5 on 2025-09-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_rename_name_of_qualification_candidate_primary_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.CharField(blank=True, null=True),
        ),
    ]
