# Generated by Django 4.2 on 2025-09-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_alter_candidate_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
