# Generated by Django 5.2.5 on 2025-09-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_alter_candidate_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='primary_credits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='primary_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
