# Generated by Django 5.2.5 on 2025-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_alter_candidate_primary_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='secondary_credits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='secondary_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
