# Generated by Django 5.2.5 on 2025-09-06 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_alter_candidate_secondary_credits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='checked_at',
            field=models.DateTimeField(blank=True, help_text='When grades were saved/checked', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='checked_by',
            field=models.ForeignKey(blank=True, help_text='User who saved/checked the grades', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_candidates', to=settings.AUTH_USER_MODEL),
        ),
    ]
