# Generated by Django 5.2.5 on 2025-09-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_remove_center_code_remove_center_name_center_comd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': 'Exam center', 'verbose_name_plural': 'Exam centers'},
        ),
    ]
