# Generated by Django 5.2.5 on 2025-09-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_alter_center_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='address',
        ),
        migrations.RemoveField(
            model_name='center',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='center',
            name='conducting_Fmn',
        ),
        migrations.RemoveField(
            model_name='center',
            name='district',
        ),
        migrations.RemoveField(
            model_name='center',
            name='state',
        ),
        migrations.AlterField(
            model_name='center',
            name='comd',
            field=models.CharField(blank=True, choices=[('SC', 'Southern Command'), ('EC', 'Eastern Command'), ('WC', 'Western Command'), ('CC', 'Central Command'), ('NC', 'Northern Command'), ('SWC', 'South Western Command'), ('ANC', 'Andaman & Nicobar Command'), ('ARTRAC', 'ARTRAC')], max_length=20),
        ),
    ]
